name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > aws_key.pem
          chmod 600 aws_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i aws_key.pem jaaz@52.35.34.186 << 'EOF'
          cd fastabproject_HNG_stage2
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart nginx
          pkill -f uvicorn || true
          nohup ./start.sh > fastapi.log 2>&1 &
          EOF
